[package]
name = "poorai-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
poorai-domain = { path = "../poorai-domain" }
regex.workspace = true
serde.workspace = true
tokio.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[lints]
workspace = true
